// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = SECRET_THING_ID;

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onDownChange();
void onUpChange();
void onThreeChange();
void onOneChange();
void onTwoChange();
void onMemoryChange();
void onAlarmChange();

bool down;
bool up;
bool three;
bool one;
bool two;
String display;
bool memory;
bool alarm;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(down, READWRITE, ON_CHANGE, onDownChange);
  ArduinoCloud.addProperty(up, READWRITE, ON_CHANGE, onUpChange);
  ArduinoCloud.addProperty(three, READWRITE, ON_CHANGE, onThreeChange);
  ArduinoCloud.addProperty(one, READWRITE, ON_CHANGE, onOneChange);
  ArduinoCloud.addProperty(two, READWRITE, ON_CHANGE, onTwoChange);
  ArduinoCloud.addProperty(display, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(memory, READWRITE, ON_CHANGE, onMemoryChange);
  ArduinoCloud.addProperty(alarm, READWRITE, ON_CHANGE, onAlarmChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
